# GitHub Linguist configuration
# This file controls how GitHub detects languages in your repository

# Mark these languages as documentation (won't count in language stats)
documentation:
  - "*.scss"
  - "*.css"
  - "*.sass"

# Mark these as vendored (generated/third-party code)
vendored:
  - "node_modules/"
  - "dist/"
  - "build/"
  - "*.min.js"
  - "*.min.css"

# Specify the main language
language: TypeScript 